/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.DTO_KhachHang;
import java.awt.Color;

/**
 *
 * @author LGNV
 */
public class dialog_FormKhachHang extends javax.swing.JDialog {

    /**
     * Creates new form dialog_FormLoaiPhong
     */
    public dialog_FormKhachHang(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getRootPane().setOpaque(false);

        this.getContentPane().setBackground(new Color(0, 0, 0, 0));
        this.setBackground(new Color(0, 0, 0, 0));
        addNew(true);
    }
    
    public String ID = "";
    public boolean checkAddNew;

    public void addNew(boolean addNew) {
        checkAddNew = addNew;
        if (!addNew) {
            btnDelete.setVisible(true);
            btnXacNhan.setText("Cập Nhật");
            ID = BLL.BLL_KhachHang.getIDTable();
        } else {
            btnXacNhan.setText("Thêm mới");
            btnDelete.setVisible(false);
        }

        repaint();
        repaint(100);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sex = new javax.swing.ButtonGroup();
        lgnvPanel1 = new lgnvswing.lgnvPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMoTa = new lgnvswing.lgnvTextField();
        lgnvButton1 = new lgnvswing.lgnvButton();
        txtCmnd = new lgnvswing.lgnvTextField();
        txtTenKhachHang = new lgnvswing.lgnvTextField();
        btnDelete = new lgnvswing.lgnvButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnXacNhan = new lgnvswing.lgnvButton();
        jLabel5 = new javax.swing.JLabel();
        txtSoDienThoai = new lgnvswing.lgnvTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNgaySinh = new lgnvswing.lgnvTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDiaChi = new lgnvswing.lgnvTextField();
        rdbNam = new javax.swing.JRadioButton();
        rdbNu = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        lgnvPanel1.setBackground(new java.awt.Color(255, 255, 255));
        lgnvPanel1.setLGNV_ShaDownAllow(true);
        lgnvPanel1.setLGNV_ShadownColor(100);
        lgnvPanel1.setLGNV_ShadownOpactity(20);
        lgnvPanel1.setLGNV_ShadownPixel(50);
        lgnvPanel1.setLGNV_borderRadius(50);
        lgnvPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(100, 89, 242));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Khách hàng");
        lgnvPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 425, 43));

        txtMoTa.setLGNV_placeholderText("Nhập Mô Tả");
        txtMoTa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMoTaActionPerformed(evt);
            }
        });
        lgnvPanel1.add(txtMoTa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 311, 46));

        lgnvButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_close_window_26px_2.png"))); // NOI18N
        lgnvButton1.setLGNV_backgroundAllow(false);
        lgnvButton1.setLGNV_lineAllow(false);
        lgnvButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        lgnvButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgnvButton1ActionPerformed(evt);
            }
        });
        lgnvPanel1.add(lgnvButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 30, 30));

        txtCmnd.setLGNV_maxCharLen(12);
        txtCmnd.setLGNV_placeholderText("Nhập chứng minh nhân dân....");
        txtCmnd.setLGNV_textType(lgnvswing.lgnvTextField.textTypeEnum.NUMBER);
        txtCmnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCmndActionPerformed(evt);
            }
        });
        lgnvPanel1.add(txtCmnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 311, 46));

        txtTenKhachHang.setLGNV_placeholderText("Nhập Tên Khách Hàng...");
        txtTenKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKhachHangActionPerformed(evt);
            }
        });
        lgnvPanel1.add(txtTenKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 311, 46));

        btnDelete.setBackground(new java.awt.Color(245, 36, 7));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Xóa");
        btnDelete.setLGNV_borderRadius(30);
        btnDelete.setLGNV_lineAllow(false);
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        lgnvPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 670, 170, 40));

        jLabel2.setText("Mô tả");
        lgnvPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 290, 20));

        jLabel3.setText("CMND Khách Hàng");
        lgnvPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 134, 290, 20));

        jLabel4.setText("Tên Khách Hàng");
        lgnvPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 290, 20));

        btnXacNhan.setBackground(new java.awt.Color(100, 89, 242));
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setText("Thêm mới");
        btnXacNhan.setLGNV_borderRadius(30);
        btnXacNhan.setLGNV_gradientBackgroundColor(new java.awt.Color(153, 153, 255));
        btnXacNhan.setLGNV_lineAllow(false);
        btnXacNhan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        lgnvPanel1.add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, 200, 50));

        jLabel5.setText("SDT");
        lgnvPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 290, 20));

        txtSoDienThoai.setLGNV_placeholderText("Nhập số điện thoại...");
        txtSoDienThoai.setLGNV_textType(lgnvswing.lgnvTextField.textTypeEnum.NUMBER);
        txtSoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDienThoaiActionPerformed(evt);
            }
        });
        lgnvPanel1.add(txtSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 311, 46));

        jLabel6.setText("Ngày Sinh");
        lgnvPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 290, 20));

        txtNgaySinh.setLGNV_placeholderText("Nhập ngày sinh :D");
        txtNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySinhActionPerformed(evt);
            }
        });
        lgnvPanel1.add(txtNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 311, 46));

        jLabel7.setText("Địa Chỉ");
        lgnvPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 290, 20));

        txtDiaChi.setLGNV_placeholderText("Nhập Địa Chỉ....");
        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });
        lgnvPanel1.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 311, 46));

        rdbNam.setBackground(new java.awt.Color(255, 255, 255));
        sex.add(rdbNam);
        rdbNam.setSelected(true);
        rdbNam.setText("Nam");
        lgnvPanel1.add(rdbNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, -1, -1));

        rdbNu.setBackground(new java.awt.Color(255, 255, 255));
        sex.add(rdbNu);
        rdbNu.setText("Nữ");
        lgnvPanel1.add(rdbNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgnvPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgnvPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMoTaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMoTaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMoTaActionPerformed

    private void txtCmndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCmndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCmndActionPerformed

    private void txtTenKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKhachHangActionPerformed

    private void lgnvButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgnvButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_lgnvButton1ActionPerformed

    private void txtSoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDienThoaiActionPerformed

    private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySinhActionPerformed

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        DTO_KhachHang KhachHang = new DTO_KhachHang();

        KhachHang = BLL.BLL_KhachHang.getDataForm();
        if (checkAddNew) {
            System.out.println("on dialog loaiPhong insert");
            BLL.BLL_KhachHang.insert(KhachHang);
        } else {
            BLL.BLL_KhachHang.update(KhachHang);
            System.out.println("on dialog loaiPhong update");

        }
        main.dialogFormKhachHang.setVisible(false);
        BLL.BLL_KhachHang.getALLData();
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        BLL.BLL_KhachHang.deleteByID(ID);
        main.dialogFormKhachHang.setVisible(false);
        System.out.println("id là : "+ID);
        BLL.BLL_KhachHang.getALLData();
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialog_FormKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialog_FormKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialog_FormKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialog_FormKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialog_FormKhachHang dialog = new dialog_FormKhachHang(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lgnvswing.lgnvButton btnDelete;
    private lgnvswing.lgnvButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private lgnvswing.lgnvButton lgnvButton1;
    private lgnvswing.lgnvPanel lgnvPanel1;
    public javax.swing.JRadioButton rdbNam;
    public javax.swing.JRadioButton rdbNu;
    private javax.swing.ButtonGroup sex;
    public lgnvswing.lgnvTextField txtCmnd;
    public lgnvswing.lgnvTextField txtDiaChi;
    public lgnvswing.lgnvTextField txtMoTa;
    public lgnvswing.lgnvTextField txtNgaySinh;
    public lgnvswing.lgnvTextField txtSoDienThoai;
    public lgnvswing.lgnvTextField txtTenKhachHang;
    // End of variables declaration//GEN-END:variables
}
