/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.awt.Color;
/**
 *
 * @author LGNV
 */
public class dialog_FormPhong extends javax.swing.JDialog {

    /**
     * Creates new form dialog_FormLoaiPhong
     */
    public dialog_FormPhong(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getRootPane().setOpaque(false);

        this.getContentPane ().setBackground (new Color (0, 0, 0, 0));
        this.setBackground (new Color (0, 0, 0, 0));
        addNew(true);
    }
    
    public void addNew(boolean addNew){
        
        if(!addNew){
            btnDelete.setVisible(true);
            btnXacNhan.setText("Cập Nhật");
        }
        else {
            btnXacNhan.setText("Thêm mới");
            btnDelete.setVisible(false);
        }

        repaint();
        repaint(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lgnvPanel1 = new lgnvswing.lgnvPanel();
        jLabel1 = new javax.swing.JLabel();
        lgnvTextField1 = new lgnvswing.lgnvTextField();
        lgnvButton1 = new lgnvswing.lgnvButton();
        lgnvTextField2 = new lgnvswing.lgnvTextField();
        btnDelete = new lgnvswing.lgnvButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnXacNhan = new lgnvswing.lgnvButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        lgnvPanel1.setBackground(new java.awt.Color(255, 255, 255));
        lgnvPanel1.setLGNV_ShaDownAllow(true);
        lgnvPanel1.setLGNV_ShadownColor(100);
        lgnvPanel1.setLGNV_ShadownOpactity(20);
        lgnvPanel1.setLGNV_ShadownPixel(50);
        lgnvPanel1.setLGNV_borderRadius(50);
        lgnvPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(100, 89, 242));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Phòng");
        lgnvPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 425, 43));

        lgnvTextField1.setLGNV_placeholderText("Mô tả phòng...");
        lgnvTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgnvTextField1ActionPerformed(evt);
            }
        });
        lgnvPanel1.add(lgnvTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 311, 46));

        lgnvButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_close_window_26px_2.png"))); // NOI18N
        lgnvButton1.setLGNV_backgroundAllow(false);
        lgnvButton1.setLGNV_lineAllow(false);
        lgnvButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        lgnvButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgnvButton1ActionPerformed(evt);
            }
        });
        lgnvPanel1.add(lgnvButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 30, 30));

        lgnvTextField2.setLGNV_placeholderText("Nhập tên phòng...");
        lgnvTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgnvTextField2ActionPerformed(evt);
            }
        });
        lgnvPanel1.add(lgnvTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 311, 46));

        btnDelete.setBackground(new java.awt.Color(245, 36, 7));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Xóa Loại Này !!");
        btnDelete.setLGNV_borderRadius(30);
        btnDelete.setLGNV_lineAllow(false);
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lgnvPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 170, 40));

        jLabel2.setText("Mô tả");
        lgnvPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 290, 30));

        jLabel3.setText("Tên Phòng");
        lgnvPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 290, 30));

        jLabel4.setText("Khu Vực");
        lgnvPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 290, 30));

        btnXacNhan.setBackground(new java.awt.Color(100, 89, 242));
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setText("Thêm mới");
        btnXacNhan.setLGNV_borderRadius(30);
        btnXacNhan.setLGNV_gradientBackgroundColor(new java.awt.Color(153, 153, 255));
        btnXacNhan.setLGNV_lineAllow(false);
        btnXacNhan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lgnvPanel1.add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 200, 50));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khu Vực 1" }));
        lgnvPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 290, 40));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Một Giường", "Hai Giường", "Một Giường Vip", "Hai Giường Vip", " " }));
        lgnvPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 290, 40));

        jLabel5.setText("Loại Phòng");
        lgnvPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 290, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgnvPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgnvPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lgnvTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgnvTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnvTextField1ActionPerformed

    private void lgnvTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgnvTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnvTextField2ActionPerformed

    private void lgnvButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgnvButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_lgnvButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialog_FormPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialog_FormPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialog_FormPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialog_FormPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialog_FormPhong dialog = new dialog_FormPhong(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lgnvswing.lgnvButton btnDelete;
    private lgnvswing.lgnvButton btnXacNhan;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private lgnvswing.lgnvButton lgnvButton1;
    private lgnvswing.lgnvPanel lgnvPanel1;
    private lgnvswing.lgnvTextField lgnvTextField1;
    private lgnvswing.lgnvTextField lgnvTextField2;
    // End of variables declaration//GEN-END:variables
}
