/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_LoaiPhong;
import DTO.DTO_LoaiPhong;
import java.awt.Color;

/**
 *
 * @author LGNV
 */
public class dialog_FormLoaiPhong extends javax.swing.JDialog {

    /**
     * Creates new form dialog_FormLoaiPhong
     */
    public dialog_FormLoaiPhong(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getRootPane().setOpaque(false);

        this.getContentPane().setBackground(new Color(0, 0, 0, 0));
        this.setBackground(new Color(0, 0, 0, 0));
        addNew(true);
    }

    boolean myAddNew = true;
    public String ID = "";

    public void addNew(boolean addNew) {
        myAddNew = addNew;
        if (!myAddNew) {
            btnDelete.setVisible(true);
            btnXacNhan.setText("Cập Nhật");
        } else {
            btnXacNhan.setText("Thêm mới");
            btnDelete.setVisible(false);
        }

        repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lgnvPanel1 = new lgnvswing.lgnvPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMoTa = new lgnvswing.lgnvTextField();
        btnClose = new lgnvswing.lgnvButton();
        txtTenLoaiPhong = new lgnvswing.lgnvTextField();
        txtGiaPhong = new lgnvswing.lgnvTextField();
        btnDelete = new lgnvswing.lgnvButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnXacNhan = new lgnvswing.lgnvButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        lgnvPanel1.setBackground(new java.awt.Color(255, 255, 255));
        lgnvPanel1.setLGNV_ShaDownAllow(true);
        lgnvPanel1.setLGNV_ShadownColor(100);
        lgnvPanel1.setLGNV_ShadownOpactity(20);
        lgnvPanel1.setLGNV_ShadownPixel(50);
        lgnvPanel1.setLGNV_borderRadius(50);
        lgnvPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(100, 89, 242));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOẠI PHÒNG");
        lgnvPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 425, 43));

        txtMoTa.setLGNV_placeholderText("Mô tả phòng...");
        txtMoTa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMoTaActionPerformed(evt);
            }
        });
        lgnvPanel1.add(txtMoTa, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 340, 310, 46));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_close_window_26px_2.png"))); // NOI18N
        btnClose.setLGNV_backgroundAllow(false);
        btnClose.setLGNV_lineAllow(false);
        btnClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        lgnvPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 30, 30));

        txtTenLoaiPhong.setLGNV_placeholderText("Nhập mã loại phòng...");
        txtTenLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenLoaiPhongActionPerformed(evt);
            }
        });
        lgnvPanel1.add(txtTenLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 311, 46));

        txtGiaPhong.setLGNV_placeholderText("Nhập Giá Phòng");
        txtGiaPhong.setLGNV_textType(lgnvswing.lgnvTextField.textTypeEnum.NUMBER_FORMAT);
        txtGiaPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaPhongActionPerformed(evt);
            }
        });
        lgnvPanel1.add(txtGiaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 311, 46));

        btnDelete.setBackground(new java.awt.Color(245, 36, 7));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Xóa Loại Này !!");
        btnDelete.setLGNV_borderRadius(30);
        btnDelete.setLGNV_lineAllow(false);
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        lgnvPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 170, 40));

        jLabel2.setText("Mô tả");
        lgnvPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 290, 20));

        jLabel3.setText("Tên Loại Phòng");
        lgnvPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 134, 290, 20));

        jLabel4.setText("Giá Phòng");
        lgnvPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 290, 20));

        btnXacNhan.setBackground(new java.awt.Color(100, 89, 242));
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setText("Thêm mới");
        btnXacNhan.setLGNV_borderRadius(30);
        btnXacNhan.setLGNV_gradientBackgroundColor(new java.awt.Color(153, 153, 255));
        btnXacNhan.setLGNV_lineAllow(false);
        btnXacNhan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        lgnvPanel1.add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 200, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgnvPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lgnvPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMoTaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMoTaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMoTaActionPerformed

    private void txtTenLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenLoaiPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenLoaiPhongActionPerformed

    private void txtGiaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaPhongActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        DTO_LoaiPhong loaiPhong = new DTO_LoaiPhong();

        loaiPhong = BLL_LoaiPhong.getDataForm();
        if (myAddNew) {
            System.out.println("on dialog loaiPhong insert");
            BLL_LoaiPhong.insert(loaiPhong);
        } else {
            BLL_LoaiPhong.update(loaiPhong);
            System.out.println("on dialog loaiPhong update");
            BLL.BLL_Phong.LoadDataCBBTenLoaiPhong(dialog_FormPhong.cbbLoaiPhong);
            BLL.BLL_Phong.LoadDataPhong(pnl_tab_Manager_Phong.tblPhong);
        }
        main.dialogFormLoaiPhong.setVisible(false);
        BLL_LoaiPhong.getALLData();
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        BLL_LoaiPhong.deleteByID(BLL_LoaiPhong.getIDTable());
        this.setVisible(false);
        BLL_LoaiPhong.getALLData();
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialog_FormLoaiPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialog_FormLoaiPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialog_FormLoaiPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialog_FormLoaiPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialog_FormLoaiPhong dialog = new dialog_FormLoaiPhong(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lgnvswing.lgnvButton btnClose;
    private lgnvswing.lgnvButton btnDelete;
    private lgnvswing.lgnvButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private lgnvswing.lgnvPanel lgnvPanel1;
    public lgnvswing.lgnvTextField txtGiaPhong;
    public lgnvswing.lgnvTextField txtMoTa;
    public lgnvswing.lgnvTextField txtTenLoaiPhong;
    // End of variables declaration//GEN-END:variables
}
