/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;

/**
 *
 * @author LGNV
 */
public class pnl_Tab_Manager extends javax.swing.JPanel {
    pnl_tab_Manager_LoaiPhong tab_Loai_Phong = main.tabLoaiPhong;
    pnl_tab_Manager_KhachHang tab_KhachHang = main.tabKhachHang;
    pnl_tab_Manager_Phong tab_Phong = main.tabPhong;
    /**
     * Creates new form pnl_Tab_Home
     */
    
    public pnl_Tab_Manager() {
        initComponents();
        pnlCenter.add(tab_Loai_Phong, "loaiphong");
        pnlCenter.add(tab_KhachHang, "khachhang");
        pnlCenter.add(tab_Phong, "phong");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lgnvPanel1 = new lgnvswing.lgnvPanel();
        lgnvPanel2 = new lgnvswing.lgnvPanel();
        lgnvPanel3 = new lgnvswing.lgnvPanel();
        btn_Tab_Manager_NhanVien = new lgnvswing.lgnvButton();
        btn_Tab_Manager_KhachHang = new lgnvswing.lgnvButton();
        btn_Tab_Manager_Phong = new lgnvswing.lgnvButton();
        btn_Tab_Manager_LoaiPhong = new lgnvswing.lgnvButton();
        btn_Tab_Manager_NhanVien_DichVu = new lgnvswing.lgnvButton();
        pnlCenter = new lgnvswing.lgnvPanel();

        setLayout(new java.awt.CardLayout());

        lgnvPanel1.setBackground(new java.awt.Color(255, 255, 255));
        lgnvPanel1.setLGNV_lineAllow(false);
        lgnvPanel1.setLayout(new java.awt.BorderLayout());

        lgnvPanel2.setBackground(new java.awt.Color(66, 139, 202));
        lgnvPanel2.setLGNV_lineAllow(false);
        lgnvPanel2.setPreferredSize(new java.awt.Dimension(250, 610));

        lgnvPanel3.setBackground(new java.awt.Color(66, 139, 202));
        lgnvPanel3.setLGNV_lineAllow(false);
        lgnvPanel3.setOpaque(true);
        lgnvPanel3.setLayout(new java.awt.GridLayout(0, 1));

        btn_Tab_Manager_NhanVien.setBackground(new java.awt.Color(66, 139, 202));
        btn_Tab_Manager_NhanVien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        btn_Tab_Manager_NhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btn_Tab_Manager_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_staff_25px.png"))); // NOI18N
        btn_Tab_Manager_NhanVien.setText("Quản Lí Nhân Viên");
        btn_Tab_Manager_NhanVien.setLGNV_enteredColor(new java.awt.Color(36, 97, 131));
        btn_Tab_Manager_NhanVien.setLGNV_lineAllow(false);
        btn_Tab_Manager_NhanVien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Tab_Manager_NhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_Tab_Manager_NhanVien.setIconTextGap(20);
        btn_Tab_Manager_NhanVien.setMargin(new java.awt.Insets(2, 0, 0, 14));
        btn_Tab_Manager_NhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Tab_Manager_NhanVienActionPerformed(evt);
            }
        });
        lgnvPanel3.add(btn_Tab_Manager_NhanVien);

        btn_Tab_Manager_KhachHang.setBackground(new java.awt.Color(66, 139, 202));
        btn_Tab_Manager_KhachHang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        btn_Tab_Manager_KhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btn_Tab_Manager_KhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_staff_25px.png"))); // NOI18N
        btn_Tab_Manager_KhachHang.setText("Quản Lí Khách Hàng");
        btn_Tab_Manager_KhachHang.setLGNV_enteredColor(new java.awt.Color(36, 97, 131));
        btn_Tab_Manager_KhachHang.setLGNV_lineAllow(false);
        btn_Tab_Manager_KhachHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Tab_Manager_KhachHang.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_Tab_Manager_KhachHang.setIconTextGap(20);
        btn_Tab_Manager_KhachHang.setMargin(new java.awt.Insets(2, 30, 2, 14));
        btn_Tab_Manager_KhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Tab_Manager_KhachHangActionPerformed(evt);
            }
        });
        lgnvPanel3.add(btn_Tab_Manager_KhachHang);

        btn_Tab_Manager_Phong.setBackground(new java.awt.Color(66, 139, 202));
        btn_Tab_Manager_Phong.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        btn_Tab_Manager_Phong.setForeground(new java.awt.Color(255, 255, 255));
        btn_Tab_Manager_Phong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_staff_25px.png"))); // NOI18N
        btn_Tab_Manager_Phong.setText("Quản Lí Phòng");
        btn_Tab_Manager_Phong.setLGNV_enteredColor(new java.awt.Color(36, 97, 131));
        btn_Tab_Manager_Phong.setLGNV_lineAllow(false);
        btn_Tab_Manager_Phong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Tab_Manager_Phong.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_Tab_Manager_Phong.setIconTextGap(20);
        btn_Tab_Manager_Phong.setMargin(new java.awt.Insets(2, 30, 2, 14));
        btn_Tab_Manager_Phong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Tab_Manager_PhongActionPerformed(evt);
            }
        });
        lgnvPanel3.add(btn_Tab_Manager_Phong);

        btn_Tab_Manager_LoaiPhong.setBackground(new java.awt.Color(66, 139, 202));
        btn_Tab_Manager_LoaiPhong.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        btn_Tab_Manager_LoaiPhong.setForeground(new java.awt.Color(255, 255, 255));
        btn_Tab_Manager_LoaiPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_staff_25px.png"))); // NOI18N
        btn_Tab_Manager_LoaiPhong.setText("Loại Phòng");
        btn_Tab_Manager_LoaiPhong.setLGNV_enteredColor(new java.awt.Color(36, 97, 131));
        btn_Tab_Manager_LoaiPhong.setLGNV_lineAllow(false);
        btn_Tab_Manager_LoaiPhong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Tab_Manager_LoaiPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_Tab_Manager_LoaiPhong.setIconTextGap(20);
        btn_Tab_Manager_LoaiPhong.setMargin(new java.awt.Insets(2, 30, 2, 14));
        btn_Tab_Manager_LoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Tab_Manager_LoaiPhongActionPerformed(evt);
            }
        });
        lgnvPanel3.add(btn_Tab_Manager_LoaiPhong);

        btn_Tab_Manager_NhanVien_DichVu.setBackground(new java.awt.Color(66, 139, 202));
        btn_Tab_Manager_NhanVien_DichVu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        btn_Tab_Manager_NhanVien_DichVu.setForeground(new java.awt.Color(255, 255, 255));
        btn_Tab_Manager_NhanVien_DichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_staff_25px.png"))); // NOI18N
        btn_Tab_Manager_NhanVien_DichVu.setText("Dịch Vụ");
        btn_Tab_Manager_NhanVien_DichVu.setLGNV_enteredColor(new java.awt.Color(36, 97, 131));
        btn_Tab_Manager_NhanVien_DichVu.setLGNV_lineAllow(false);
        btn_Tab_Manager_NhanVien_DichVu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Tab_Manager_NhanVien_DichVu.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_Tab_Manager_NhanVien_DichVu.setIconTextGap(20);
        btn_Tab_Manager_NhanVien_DichVu.setMargin(new java.awt.Insets(2, 30, 2, 14));
        lgnvPanel3.add(btn_Tab_Manager_NhanVien_DichVu);

        javax.swing.GroupLayout lgnvPanel2Layout = new javax.swing.GroupLayout(lgnvPanel2);
        lgnvPanel2.setLayout(lgnvPanel2Layout);
        lgnvPanel2Layout.setHorizontalGroup(
            lgnvPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lgnvPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lgnvPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
        );
        lgnvPanel2Layout.setVerticalGroup(
            lgnvPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lgnvPanel2Layout.createSequentialGroup()
                .addComponent(lgnvPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 116, Short.MAX_VALUE))
        );

        lgnvPanel1.add(lgnvPanel2, java.awt.BorderLayout.LINE_START);

        pnlCenter.setBackground(new java.awt.Color(255, 255, 255));
        pnlCenter.setLGNV_lineAllow(false);
        pnlCenter.setLayout(new java.awt.CardLayout());
        lgnvPanel1.add(pnlCenter, java.awt.BorderLayout.CENTER);

        add(lgnvPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Tab_Manager_NhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Tab_Manager_NhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Tab_Manager_NhanVienActionPerformed

    private void btn_Tab_Manager_PhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Tab_Manager_PhongActionPerformed
        chooseTab("phong");
    }//GEN-LAST:event_btn_Tab_Manager_PhongActionPerformed

    private void btn_Tab_Manager_KhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Tab_Manager_KhachHangActionPerformed
        chooseTab("khachhang");
    }//GEN-LAST:event_btn_Tab_Manager_KhachHangActionPerformed

    private void btn_Tab_Manager_LoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Tab_Manager_LoaiPhongActionPerformed
        chooseTab("loaiphong");
    }//GEN-LAST:event_btn_Tab_Manager_LoaiPhongActionPerformed

    public void chooseTab(String nameTab){
        CardLayout layout = (CardLayout) pnlCenter.getLayout();
        layout.show(pnlCenter, nameTab);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lgnvswing.lgnvButton btn_Tab_Manager_KhachHang;
    private lgnvswing.lgnvButton btn_Tab_Manager_LoaiPhong;
    private lgnvswing.lgnvButton btn_Tab_Manager_NhanVien;
    private lgnvswing.lgnvButton btn_Tab_Manager_NhanVien_DichVu;
    private lgnvswing.lgnvButton btn_Tab_Manager_Phong;
    private lgnvswing.lgnvPanel lgnvPanel1;
    private lgnvswing.lgnvPanel lgnvPanel2;
    private lgnvswing.lgnvPanel lgnvPanel3;
    private lgnvswing.lgnvPanel pnlCenter;
    // End of variables declaration//GEN-END:variables
}
