/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author LGNV
 */
public class pnl_Tab_Home extends javax.swing.JPanel {

    /**
     * Creates new form pnl_Tab_Home
     */
    public pnl_Tab_Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lgnvPanel1 = new lgnvswing.lgnvPanel();
        lgnvPanel2 = new lgnvswing.lgnvPanel();
        lgnvPanel3 = new lgnvswing.lgnvPanel();
        lgnvButton1 = new lgnvswing.lgnvButton();
        lgnvButton2 = new lgnvswing.lgnvButton();
        lgnvButton3 = new lgnvswing.lgnvButton();
        lgnvButton4 = new lgnvswing.lgnvButton();
        lgnvButton5 = new lgnvswing.lgnvButton();
        pnlCenter = new lgnvswing.lgnvPanel();

        setLayout(new java.awt.CardLayout());

        lgnvPanel1.setBackground(new java.awt.Color(255, 255, 255));
        lgnvPanel1.setLGNV_lineAllow(false);
        lgnvPanel1.setLayout(new java.awt.BorderLayout());

        lgnvPanel2.setBackground(new java.awt.Color(66, 139, 202));
        lgnvPanel2.setLGNV_lineAllow(false);
        lgnvPanel2.setPreferredSize(new java.awt.Dimension(250, 610));

        lgnvPanel3.setBackground(new java.awt.Color(66, 139, 202));
        lgnvPanel3.setLGNV_lineAllow(false);
        lgnvPanel3.setOpaque(true);
        lgnvPanel3.setLayout(new java.awt.GridLayout(0, 1));

        lgnvButton1.setBackground(new java.awt.Color(66, 139, 202));
        lgnvButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        lgnvButton1.setForeground(new java.awt.Color(255, 255, 255));
        lgnvButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_staff_25px.png"))); // NOI18N
        lgnvButton1.setText("AHihi");
        lgnvButton1.setLGNV_lineAllow(false);
        lgnvButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lgnvButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        lgnvButton1.setIconTextGap(20);
        lgnvButton1.setMargin(new java.awt.Insets(2, 0, 0, 14));
        lgnvButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgnvButton1ActionPerformed(evt);
            }
        });
        lgnvPanel3.add(lgnvButton1);

        lgnvButton2.setBackground(new java.awt.Color(66, 139, 202));
        lgnvButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        lgnvButton2.setForeground(new java.awt.Color(255, 255, 255));
        lgnvButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_staff_25px.png"))); // NOI18N
        lgnvButton2.setText("Ahehe");
        lgnvButton2.setLGNV_lineAllow(false);
        lgnvButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lgnvButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        lgnvButton2.setIconTextGap(20);
        lgnvButton2.setMargin(new java.awt.Insets(2, 30, 2, 14));
        lgnvPanel3.add(lgnvButton2);

        lgnvButton3.setBackground(new java.awt.Color(66, 139, 202));
        lgnvButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        lgnvButton3.setForeground(new java.awt.Color(255, 255, 255));
        lgnvButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_staff_25px.png"))); // NOI18N
        lgnvButton3.setText("Ahhihe");
        lgnvButton3.setLGNV_lineAllow(false);
        lgnvButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lgnvButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        lgnvButton3.setIconTextGap(20);
        lgnvButton3.setMargin(new java.awt.Insets(2, 30, 2, 14));
        lgnvButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgnvButton3ActionPerformed(evt);
            }
        });
        lgnvPanel3.add(lgnvButton3);

        lgnvButton4.setBackground(new java.awt.Color(66, 139, 202));
        lgnvButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        lgnvButton4.setForeground(new java.awt.Color(255, 255, 255));
        lgnvButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_staff_25px.png"))); // NOI18N
        lgnvButton4.setText("ahehi");
        lgnvButton4.setLGNV_lineAllow(false);
        lgnvButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lgnvButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        lgnvButton4.setIconTextGap(20);
        lgnvButton4.setMargin(new java.awt.Insets(2, 30, 2, 14));
        lgnvPanel3.add(lgnvButton4);

        lgnvButton5.setBackground(new java.awt.Color(66, 139, 202));
        lgnvButton5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        lgnvButton5.setForeground(new java.awt.Color(255, 255, 255));
        lgnvButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_staff_25px.png"))); // NOI18N
        lgnvButton5.setText("Ahihih");
        lgnvButton5.setLGNV_lineAllow(false);
        lgnvButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lgnvButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        lgnvButton5.setIconTextGap(20);
        lgnvButton5.setMargin(new java.awt.Insets(2, 30, 2, 14));
        lgnvPanel3.add(lgnvButton5);

        javax.swing.GroupLayout lgnvPanel2Layout = new javax.swing.GroupLayout(lgnvPanel2);
        lgnvPanel2.setLayout(lgnvPanel2Layout);
        lgnvPanel2Layout.setHorizontalGroup(
            lgnvPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lgnvPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lgnvPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
        );
        lgnvPanel2Layout.setVerticalGroup(
            lgnvPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lgnvPanel2Layout.createSequentialGroup()
                .addComponent(lgnvPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 417, Short.MAX_VALUE))
        );

        lgnvPanel1.add(lgnvPanel2, java.awt.BorderLayout.LINE_START);

        pnlCenter.setBackground(new java.awt.Color(255, 255, 255));
        pnlCenter.setLGNV_lineAllow(false);

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );

        lgnvPanel1.add(pnlCenter, java.awt.BorderLayout.CENTER);

        add(lgnvPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void lgnvButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgnvButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnvButton1ActionPerformed

    private void lgnvButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgnvButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnvButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lgnvswing.lgnvButton lgnvButton1;
    private lgnvswing.lgnvButton lgnvButton2;
    private lgnvswing.lgnvButton lgnvButton3;
    private lgnvswing.lgnvButton lgnvButton4;
    private lgnvswing.lgnvButton lgnvButton5;
    private lgnvswing.lgnvPanel lgnvPanel1;
    private lgnvswing.lgnvPanel lgnvPanel2;
    private lgnvswing.lgnvPanel lgnvPanel3;
    private lgnvswing.lgnvPanel pnlCenter;
    // End of variables declaration//GEN-END:variables
}
